export const FETCH_DONORS = 'FETCH_DONORS'
export const FETCH_DONOR = 'FETCH_DONOR'
export const SEARCH_DONORS = 'SEARCH_DONORS'

export const TOGGLE_DONOR_DIALOG = 'TOGGLE_DONOR_DIALOG'
export const TOGGLE_SITE_LOADING = 'TOGGLE_SITE_LOADING'

export const FETCH_DISTRICTS = 'FETCH_DISTRICTS'
export const FETCH_AREAS = 'FETCH_AREAS'

export const FETCH_HOSPITALS = 'FETCH_HOSPITALS'

export const FETCH_BLOOD_REQUEST = 'FETCH_BLOOD_REQUEST'
export const FETCH_BLOOD_REQUESTS = 'FETCH_BLOOD_REQUESTS'
export const TOGGLE_BLOOD_REQUEST_DIALOG = 'TOGGLE_BLOOD_REQUEST_DIALOG'


export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTRATION = 'REGISTRATION'
export const UPDATE_USER = "UPDATE_USER"
export const FETCH_USER = "FETCH_USER"
export const TOGGLE_VALIDATE_ERRORS = 'TOGGLE_VALIDATE_ERRORS'

export const RESET_REQUEST = 'RESET_REQUEST'
export const RESET_OTP_VERIFY = 'RESET_OTP_VERIFY'
export const RESET_PASSWORD = 'RESET_PASSWORD'


export const TOGGLE_DIALOG = 'TOGGLE_DIALOG'
export const TOGGLE_PROFILE_DIALOG = 'TOGGLE_PROFILE_DIALOG'

export const TOGGLE_REGISTER_FORM = 'TOGGLE_REGISTER_FORM'
export const TOGGLE_LOGIN_FORM = 'TOGGLE_LOGIN_FORM'

export const AUTH_FORM_TYPE = "AUTH_FORM_TYPE"
