export const FETCH_DONORS = 'FETCH_DONORS'
export const FETCH_DONOR = 'FETCH_DONOR'
export const SEARCH_DONORS = 'SEARCH_DONORS'

export const TOGGLE_DONOR_DIALOG = 'TOGGLE_DONOR_DIALOG'
export const TOGGLE_SITE_LOADING = 'TOGGLE_SITE_LOADING'

export const FETCH_DISTRICTS = 'FETCH_DISTRICTS'
export const FETCH_AREAS = 'FETCH_AREAS'

export const FETCH_HOSPITALS = 'FETCH_HOSPITALS'

export const FETCH_BLOOD_REQUEST = 'FETCH_BLOOD_REQUEST'
export const FETCH_BLOOD_REQUESTS = 'FETCH_BLOOD_REQUESTS'
export const TOGGLE_BLOOD_REQUEST_DIALOG = 'TOGGLE_BLOOD_REQUEST_DIALOG'
